### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Pali1231** [DenisMirand4/Bot_Albion_Labour#1]
hi . 
i got os.remove("tempo_ilha.txt") error if you can help me pls ADD discord ::  NAGYVEZÉR
#6040  ::

**Comment by Pali1231** [comment]
Help me bro :D

**Comment by DenisMirand4** [comment]
Sup, sorry for the delay to answer. I believe that the error above was fixed in the last update. But you need to edit some parts of the code to run in your islands. I will send a invite in your discord for future questions.
